---
- name: Install Docker on bastion and app nodes
  hosts: bastion
  become: true

  roles:
#    - docker --> docker, containerd, and k8s are installed using the bootstrap on provisioning with terraform
    - jenkins
    - argocd
